### ISSUE TITLE
Modificar workflow libs

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-lib#105]
El workflow debe comprobar en los **push y PR** de las **ramas master y develop**:
- Se instalan bien las dependencias (npm install)
- Que la librería se transpila correctamente (se hace bien el tsc)
- Se pasan los tests correspondientes (npm test)

Si alguno de los check falla, se debe notificar como que no ha pasado el CI.

**Comment by anthares101** [comment]
Already done
