### ISSUE TITLE
UP2 - Change smart contracts addresses in the lib config and check all the examples work

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#116]

**Comment by rober12** [comment]
The address of the smart contracts upgradeables

https://github.com/alastria/temp-alastriaID-truffle-contracts/blob/develop/addresses.json

**Comment by DrankoLQ** [comment]
I've updated the address of the smart contracts and test the examples but it doesn't work. It may be I haven't done the changes correctly or we have to update more things, so here is the list of things I have done

- Clean npm install in `alastria-identity-example` repository
- Update the file `alastria-identity-example/node-modules/alastria-identity-lib/dist/config.js` that contains the addresses of the smart contract with the new addresses
- Run the script `alastira-identity-example/dev-tools/createMockIdentities.sh` to start testing the examples, but they fail

![image](https://user-images.githubusercontent.com/8750071/100222986-2f5a4680-2f1b-11eb-9561-93845daba9ea.png)

**Comment by VictorNS69** [comment]
We have detected that certain changes need to be made in https://github.com/alastria/alastria-identity-lib and https://github.com/alastria/temp-alastriaID-truffle-contracts.

We are looking at it right now.

**Comment by DrankoLQ** [comment]
Perfect! Anything I can help, just tell me 🙂

**Comment by VictorNS69** [comment]
@DrankoLQ  check #137 if you change the `package.json`

**Comment by DrankoLQ** [comment]
Perfect!

**Comment by DrankoLQ** [comment]
I have made some changes to tests the new contracts but it looks like something is not working correctly or I'm missing some more changes

In the example repo, I've updated the lib dependency to use the branch I've created with the changes needed in the lib (https://github.com/alastria/alastria-identity-example/compare/develop...feature/support-upgradeable-contracts=

In the other hand, the lib changes are here https://github.com/alastria/alastria-identity-lib/compare/develop...feature/support-upgradeable-contracts: I've updated the contracts addresses and added the JSON ABI files generated by Truffle after the compilation

If I'm missing any change to test the new contracts feel free to comment them so I can keep testing them 🙂, I've run out of ideas

**Comment by anthares101** [comment]
I have updated the smart contracts addresses and also the JSON abi files in the alastria identity lib [support-upgradeable-contracts](https://github.com/alastria/alastria-identity-lib/tree/feature/support-upgradeable-contracts) branch.

After that i tested the examples in the [support-upgradeable-contracts](https://github.com/alastria/alastria-identity-example/tree/feature/support-upgradeable-contracts) branch in the alastria identity example repository:

![image](https://user-images.githubusercontent.com/33127189/114403520-28b82d00-9ba5-11eb-948f-dea41b729af7.png)

Looks like now the first example is working but the rest of them are still failing, maybe im missing something.

**Comment by VictorNS69** [comment]
Thanks for the update!

The Entity examples (`exampleFirstEntity/2.addEntity.js` and `exampleEntities`) should not work. Also, I recommend you to run the examples one by one, as you will have a more detailed trace. For example, you must check the addresses that are being used in the first non-Entity failing example you have (`exampleFirstEntity/3.addIdentityIssuer.js`).

I think the use keystores in the examples must change. When a new deploy is done, this [EOA](https://github.com/alastria/alastria-identity-example/blob/master/keystores/subject2-643266eb3105f4bf8b4f4fec50886e453f0da9ad.json) is the "first issuer and service provider". So you have to use this keystore as the "issuer" in `exampleFirstEntity/3.addIdentityIssuer.js`.

**Comment by anthares101** [comment]
After changing the keystores and updating some examples to match the changes, i run the examples 1 by 1 and these are the results:
- exampleAuthentication (Errors: 0)
- exampleCreateAlastriaID (Errors: 4.createSubject2AlastriaID --> `Error: Transaction has been reverted by the EVM`)
- exampleCredentials (Errors: 0)
- exampleEntities (Errors: All --> `Error: Returned values aren't valid, did it run Out of Gas?`)
- exampleFirstEntity (Errors: 2.addEntity --> `Error: Transaction has been reverted by the EVM`)
- exampleIssuer (Errors: 1.addEntity --> `Error: Transaction has been reverted by the EVM`)
- examplePresentations (Errors: 0)
- examplePublicKey (Errors: 0)
- exampleServiceProvider (Errors: 1.addEntity --> `Error: Transaction has been reverted by the EVM`)
- exampleTokens (Errors: 0)
The only not expected error is exampleCreateAlastriaID/4.createSubject2AlastriaID.js, maybe the keystore that we are using is not correct?

**Comment by VictorNS69** [comment]
> exampleCreateAlastriaID (Errors: 4.createSubject2AlastriaID --> Error: Transaction has been reverted by the EVM)

I think this is normal, maybe there is a problem with the keystores. 

> exampleEntities (Errors: All --> Error: Returned values aren't valid, did it run Out of Gas?)
> exampleFirstEntity (Errors: 2.addEntity --> Error: Transaction has been reverted by the EVM)
> exampleIssuer (Errors: 1.addEntity --> Error: Transaction has been reverted by the EVM)

This is expected to happen now since the Entities Smart Contract is not deployed (we are working on it)

> exampleServiceProvider (Errors: 1.addEntity --> Error: Transaction has been reverted by the EVM)

Also expected (see above)

**Comment by anthares101** [comment]
Cool then, all the changes are in the branch yes. Keep in mind that it is using the alastria identity lib [support-upgradeable-contracts](https://github.com/alastria/alastria-identity-lib/tree/feature/support-upgradeable-contracts) branch.

**Comment by VictorNS69** [comment]
Please @anthares101 instead of using this [keystore](https://github.com/alastria/alastria-identity-example/blob/feature/support-upgradeable-contracts/keystores/subject2-6e3976aeaa3a59e4af51783cc46ee0ffabc5dc11.json) for the subject 2, create a new one (with the same password).

The keystore with address `0x6e3976aeaa3a59e4af51783cc46ee0ffabc5dc11` is used as the admin account when deploying (https://github.com/alastria/temp-alastriaID-truffle-contracts/blob/develop/truffle-config.js#L129), so we really don't want to use this keystore for other purpose.

Also, the actual ["admin" keystore](https://github.com/alastria/alastria-identity-example/blob/feature/support-upgradeable-contracts/keystores/admin-643266eb3105f4bf8b4f4fec50886e453f0da9ad.json) should be renamed to "firstIdentity" as the [truffle-contracts repo](https://github.com/alastria/temp-alastriaID-truffle-contracts/blob/develop/truffle-config.js#L128) is doing.

**Comment by anthares101** [comment]
I updated the admin keystore file name and also created a new keystore for subject2. I ran the examples again and the 4.createSubject2AlastriaID example is working now too:

- exampleAuthentication (Errors: 0)
- exampleCreateAlastriaID (Errors: 0)
- exampleCredentials (Errors: 0)
- exampleEntities (Errors: All --> `Error: Returned values aren't valid, did it run Out of Gas?`)
- exampleFirstEntity (Errors: 2.addEntity --> `Error: Transaction has been reverted by the EVM`)
- exampleIssuer (Errors: 1.addEntity --> `Error: Transaction has been reverted by the EVM`)
- examplePresentations (Errors: 0)
- examplePublicKey (Errors: 0)
- exampleServiceProvider (Errors: 1.addEntity --> `Error: Transaction has been reverted by the EVM`)
- exampleTokens (Errors: 0)

**Comment by VictorNS69** [comment]
Do we want to push this changes after the #142  and #144 or we can do it before?

**Comment by anthares101** [comment]
We could push them before, i don't think it really matters. If the dependencies works with the old smart contracts i think they should work fine with the new ones.
