### ISSUE TITLE
Revisar error en la dependencia de "ethereumjs-tx"

### ISSUE THREAD

**Issue by cmoralesdiego** [alastria/alastria-identity-lib#117]
Buenas,

Estamos intentando instalar la librería en el proyecto donde queremos integrarla, al hacer el `npm install --save github:alastria/alastria-identity-lib.git#develop` desde nuestro src, nos da un error en los scripts que se ejecutan al final, diciendo lo siguiente:
```
Turn off this advice by setting config variable advice.detachedHead to false

src/UserIdentity.ts:77:18 - error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.

77       const tx = new EthereumTxAll(transaction)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

Alguna idea de dicho error?. Gracias. O bien por aquí o por el slack me podéis encontrar. Ya sabéis.

**Comment by cmoralesdiego** [comment]
Lo hemos solucionando cambiando la linea 3 de UserIdentity con lo siguiente:  const EthereumTxAll = require ("ethereumjs-tx");

**Comment by VictorNS69** [comment]
Hola, ese error que comentas era porque la versión más actual de `ethereumjs-tx` ha cambiado respecto a la versión que usábamos hasta ahora. Cómo bien dices, la solución era cambiar cómo estaba escrito el `require`.

**Comment by VictorNS69** [comment]
This issue will be fixed in #119
