### ISSUE TITLE
Add interfaces to tokensFactory

### ISSUE THREAD

**Issue by onmax** [alastria/alastria-identity-lib#118]
Lets be clear: The [tokensFactory.ts](https://github.com/alastria/alastria-identity-lib/blob/master/src/tokenFactory/tokensFactory.ts) is a little bit chaotic. My aim for now is to improve the code in that file in my following issues. Starting with the types for each JWT, so it is easier for the developers use this library.

A interfaces file already exists but I will be reestructure it to a new folder so follows the standards and I will create new interfaces

**Comment by rober12** [comment]
Closes because the code has become deprecated
