### ISSUE TITLE
Check why createAlastriaIdentity is not storing the public key in besu networks

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-lib#136]
It sems that the function `createAlastriaIdentity` is not working properly. When you use this function, and then try to get the public key with `getCurrentPublicKey` returns an empty string

**Comment by alejandroalffer** [comment]
Hi! Seems nobody has started this issue. @VictorNS69 , if just bring up a node un B network... and test the problem. Best regards!

**Comment by alejandroalffer** [comment]
Both Hyperldger BESU and Consensys GoQuorum based in Geth1.9 don't use local accounts anymore (unless using --allow-insecure-unlock in GoQuorum)

I'm working in truffle version that works in both impementations using BIT39 nmemonics

**Comment by Mashenka-ad** [comment]
Executed 1.getSubject1CurrentPublicKey.js in BESU network with the following did
"did:ala:besu:redB:8b76ed646df9da691c5e534f973b2e12bd40cce4"

Obtained log:
RESULT -----> 2c978317b40b91a8389729f1b8af3c83a76d3aca68e3fd69d7fc3d8a09d2b8d78d1ede19be52cb2bca3d1558b1faa4fa39797d93bd6d44f4e1b90d11d10d91be
Which is the correct public key.
Entity was created using a mnemonic to generate the keystore.

**Comment by VictorNS69** [comment]
That's a very good new!

Can you try to get the firstIdentityWallet public key too?

**Comment by Mashenka-ad** [comment]
What's their DID on besu?

**Comment by VictorNS69** [comment]
I don't know. You should check the identityKeys of the address `0x643266eb3105f4bf8b4f4fec50886e453f0da9ad` as it is the EOA of the "firstIdentityWallet".

Then you will know the Proxy address :smile:

**Comment by Mashenka-ad** [comment]
I think I found it

Executing 1.getSubject1CurrentPublicKey.js in BESU
RESULT -----> aca7aa42e831f41b6f246d089fbcabe73e1c6ce01a1bb5d944fda4e148e1d6930f6ebb5138b1d103e3e384c893962a238e4088a549bfe84867da96942931f69a

**Comment by VictorNS69** [comment]
Seems fine to me.

We are closing this issue as it seems to be already fixed.

Thanks for your testing @Mashenka-ad
