### ISSUE TITLE
Modify "compile" section in package.json

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-lib#137]
I think this issue belongs to https://github.com/alastria/alastria-identity, not in this repo.

The `compile` script is defined in [package.json of `alastria-identity-lib`](https://github.com/alastria/alastria-identity-lib/blob/develop/package.json#L12) as:
```
"compile": "git clone --branch mvp0.1 https://github.com/alastria/alastria-identity.git; node src/configFile.js; tsc",
```

But in Windows the character `;` is a paeter separator instead of a command separator. It should be defined as:
```
"compile": "git clone --branch mvp0.1 https://github.com/alastria/alastria-identity.git && node src/configFile.js && tsc",
```

_Originally posted by @rbarriuso in https://github.com/alastria/alastria-wallet/issues/86#issuecomment-735755647_

**Comment by glalloue** [comment]
I confirm the identification of the problem.
Using local download of this lib and modifying package.json as written above solve the issue.
