### ISSUE TITLE
Create new Artifact "AlastriaIdentityRecovery" (AIR)

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-identity-lib#150]
We need to add a new JWT object in the lib.

The object must have the following format: https://github.com/alastria/alastria-identity/wiki/Artifacts-and-User-Stories-Definitions#04-alastria-identity-recovery-air

**Note that at the moment, the Smart Contracts don't implement the "recover Alastria Identity" functionality.**

**Comment by rober12** [comment]
This object will no longer be necessary. It is closed because it is obsolete
