### ISSUE TITLE
Compatibility with node14

### ISSUE THREAD

**Issue by phabos** [alastria/alastria-identity-lib#160]
Hello,

We are working with alastria-identity-lib for a decentralized identity projet in our company.

But we are working with node version 14. So we had to make a fork of `alastria-identity-lib` and `alastria-identity` in order to upgrade the deps and be compatible with node14.

Are you interrested in a pull request for this upgrade ? 
If not, is it planned in your roadmap to make this update for node 14 compatibility ?

Thank you for your reply

**Comment by VictorNS69** [comment]
Hi @phabos !

**Which branch are you using in your project?** I think that Node v14 is working well in develop, but maybe not in the master branch. 

We expect to publish a new release of the library soon in which several aspects are corrected and upgradeable Smart Contracts are consumed (the master version works with the old contracts that have been improved).

**Comment by phabos** [comment]
Hi @VictorNS69 

Thank you for your quick reply !
We used the branch master both for `alastria-identity-lib` and `alastria-identity`.
We will give a try for the develop branch !

Does it mean we have to redeploy the smart contracts in our alastria node in order to make the develop branch to work well ?
Thx

**Comment by VictorNS69** [comment]
If you want to work with the upgradable Smart Contracts, you need to use:
- [Alastria Identity Lib (develop branch)](https://github.com/alastria/alastria-identity-lib/tree/develop)
- [AlastriaID truffle Contracts (develop branch)](https://github.com/alastria/alastriaID-truffle-contracts)

Note that the Alastria Identity Lib (in develop) will work with the AlastriaID truffle Contracts by default. The repository [Alastria Identity](https://github.com/alastria/alastria-identity) has the first version of the Smart Contracts. It means that these SCs are not upgradeables.

We expect to release the new version this summer, but we are unable to give an exact date at this time.

**Comment by VictorNS69** [comment]
If you consider that this issue has already been solved, and you have no further problems, it can be closed.

On the other hand, if you still have problems and/or doubts, we still keep the thread to give support.

I look forward to your reply.
