### ISSUE TITLE
FIX-2. DIDs en vez de AlastriaProxy address

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#44]
Modificar todas las funciones para que las librerías funcionen por DID. Internamente parsearán el mismo para obtener el AlastriaProxy address e invocar sin cambios a los Smart Contracts

**Comment by Saithan16** [comment]
Creado pull request de esta tarea

**Comment by DaniRumpi** [comment]
Muy buenas, he revisado el codifo que está en la rama feature/44-ProxyAddressToDIDs y creo que faltaría por modificar en el identityManager.
Muchas gracias!
