### ISSUE TITLE
FIX-1. Callback en Presentation Requests

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#45]
Incluir el campo "cbu" en la función createPresentationRequest en tokensFactory https://github.com/alastria/alastria-identity-lib/blob/develop/src/tokenFactory/tokensFactory.ts 

Incluir el cambio en la especificación oficial https://github.com/alastria/alastria-identity/wiki/Alastria-DID-Method-Specification-(Quorum-version)#5-presentation-request

**Comment by msalitu** [comment]
Hola, @rober12 ya incluyó el cambio en el documento de especificación. @amoral-eurogestion si tienes cualquier pregunta, por favor, no dudes en contactarnos

**Comment by amoral-eurogestion** [comment]
Buenas @msalitu, ¿Me podrías indicar sobre que rama realizo los cambios?

**Comment by VictorNS69** [comment]
> Buenas @msalitu, ¿Me podrías indicar sobre que rama realizo los cambios?

Hola @amoral-eurogestion , hay que crear una nueva rama desde develop. No hemos estipulado ninguna nomenclatura. Aún así, los compañeros están usando _feature/NUMERO_ISSUE_TITULO_.

Por ejemplo con _"44-ProxyAddressToDIDs"_.
