### ISSUE TITLE
COVID-1. Consultar validez clave pública

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#47]
Sin modificar los Smart Contracts actuales, se trata de añadir una función en la librería que dada una fecha, una clave pública y un DID, haga las consultas pertinentes para devolver un bool indicando si esa clave pública era válida en ese momento para ese DID.

Tras implementar esa función en la librería, habría que añadir un example.

**Comment by nmanero** [comment]
Acabo de subir una propuesta que aprovecha el método getPublicKeyStatus que ya existía y con su resultado, reviso las fechas para ver la validez.
Quería también testearlo evitando la conexión a la cadena, usando stubs de la función desarrollada "isPublicKeyValidForDate".
El problema venía con que si ese método llama a getPublicKeyStatus, no podía hacer stub, ya que internamente no usaba el método mockeado y usaba una instancia nueva. Para conseguirlo, he tenido que hacer que el método isPublicKeyValidForDate que he desarrollado, llame a la función a través del transactionFactory, que es el que tengo stub.
Comentamos.

**Comment by VictorNS69** [comment]
> Acabo de subir una propuesta que aprovecha el método getPublicKeyStatus que ya existía y con su resultado, reviso las fechas para ver la validez.
> Quería también testearlo evitando la conexión a la cadena, usando stubs de la función desarrollada "isPublicKeyValidForDate".
> El problema venía con que si ese método llama a getPublicKeyStatus, no podía hacer stub, ya que internamente no usaba el método mockeado y usaba una instancia nueva. Para conseguirlo, he tenido que hacer que el método isPublicKeyValidForDate que he desarrollado, llame a la función a través del transactionFactory, que es el que tengo stub.
> Comentamos.

He revisado los cambios que has hecho en la rama y me parece todo bien lo que he visto. 

Lo que no he visto es algún script de ejemplo en el repo de "examples" (los test unitarios si los he visto y están genial). **Comentamos con el resto del equipo esta propuesta**.

Gracias!

**Comment by nmanero** [comment]
Guay. No sabía lo de los examples, ya me decís cómo lo hacéis para las otras veces

**Comment by VictorNS69** [comment]
> Guay. No sabía lo de los examples, ya me decís cómo lo hacéis para las otras veces

Básicamente lo que hacemos (o intentamos hacer) es que por **cada función pública de la librería tenemos algún script de ejemplo** (que sirve como test y como guión de uso) **en el repo de "examples" (https://github.com/alastria/alastria-identity-example)**.

Así, por ejemplo, si queremos usar la función _addSubjectCredential_, se puede mirar el siguiente ejemplo: https://github.com/alastria/alastria-identity-example/blob/develop/exampleCredentials/1.addSubject1Credential.js para saber cómo ha de usarse y con qué datos.

Adicionalmente, me parece muy **buena idea** (y hay que continuar llevándola a cabo) la de **realizar test unitarios**.

**Comment by nmanero** [comment]
Perfecto y dónde integrarías dentro de todos esos test de integración el uso de este método de validación de la clave en una fecha fecha, porque estuve mirando en su momento tests del método getPublicKeyStatus pero no lo encontré en los examples

**Comment by msalitu** [comment]
Muchas gracias a ambos. Normalmente creamos dos issues para este tipo de tareas:
- un issue para implementar en la librería
- otro issue para desarrollar el ejemplo en el repositorio https://github.com/alastria/alastria-identity-example. En este caso, acabo de crearlo https://github.com/alastria/alastria-identity-example/issues/46

**Comment by nmanero** [comment]
He actualizado esta rama con los cambios para que funcione bien y los tests actualizados

**Comment by VictorNS69** [comment]
> He actualizado esta rama con los cambios para que funcione bien y los tests actualizados

Si ya está la tarea para revisión, por favor, crea una PR.
