### ISSUE TITLE
COVID-2.7 Test DIDs

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#51]
https://github.com/alastria/alastria-identity/wiki/Alastria-DID-Method-Specification-(Quorum-version)#21-alastria-did-scheme

**Comment by nmanero** [comment]
Qué es lo que se espera que testee el integrador sobre los DIDs, porque este valor puede estar integrado en otros lugares, como por ejemplo la credentian en el campo kid. ¿Por tanto, para este test concreto, cuál se espera que sea el input por parte del integrador?

**Comment by msalitu** [comment]
Sugiero que sea un test muy sencillo. El input es un string, el código tiene que parsearlo comprobando que tiene el número de campos adecuados. 
"did:ala:" + network + ":" + networkID + ":" + proxyAddress
Que cumplen las condiciones descritas en la especficicación:
Debe comenzar con el valor fijo "did"
El identificador del modelo "ala" debe ser fijo 
En network debe ser "quor" o "fabr"
En network id no se puede comprobar el valor porque podría ser "redB", "redT", "redH" u otros como "ebsi"
En proxyAddress se debe comprobar simplemente el formato, que es un número hexadecimal 
Retorna true o false

Por favor, cualquier idea adicional o corrección de planteamiento es bienvenida

**Comment by nmanero** [comment]
Perfecto, esa es fácil. Además podemos añadir que en el resto de modelos, los que incluyan también un DID, se valide allí también

**Comment by nmanero** [comment]
Acabo de subir la estructura base en la rama #49 y el test de did en esta rama, que depende de la otra.
Creo que se puede usar esta rama para continuar con el resto de validaciones. Comentamos si no se entiende

**Comment by msalitu** [comment]
Hola Nicolás, tiene muy buena pinta, ¿qué otros vendors además de Alastria prevees que puedan existir?

**Comment by nmanero** [comment]
Ah, la idea era que cada integrador copie ahi dentro su estructura tal y como indicamos/indicaremos en el readme y ejecute npm test
El de alastria está puesto si fuera un integrador de ejemplo, igual vale la pena cambiar el nombre de la carpeta y en lugar de "alastria" que se llame "alastria_as_example" o algo así...

**Comment by msalitu** [comment]
¡Ah! Ahora sí lo entiendo. A lo mejor podemos poner "integrator_1" o "vendor_1" ¿qué te parece?

**Comment by nmanero** [comment]
Perfecto, como prefieras

**Comment by VictorNS69** [comment]
Se ha cerrado por https://github.com/alastria/alastria-identity-JSON-objects/pull/2
