### ISSUE TITLE
COVID-3 Check lib compatibility with new Smart Contracts

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#63]
Update Smart Contracts addresses. It is important to change the branch where the lib takes the address from to "master" instead of "develop" by default.

Then, all the examples should be run while checking if they work properly.

Some bugs may be identified, so new issues should be opened.

**Comment by nmanero** [comment]
I don't know how to write which have been checked by me. I write them here and we can change them if it's better:

- AlastriaCredentialRegistry
    - issuerCredentialList -> Not used by the library
    - getSubjectCredentialList -> Compatible
    - version -> Not used by the library
    - getSubjectCredentialStatus -> Compatible
    - getCredentialStatus -> Compatible with the lib. Not used by the examples
    - previousPublishedVersion -> Not used by the library
    - subjectCredentialRegistry -> Not used by the library
    - getIssuerCredentialStatus -> Compatible
    - subjectCredentialList -> EXPECTS 2 parameters but lib only sends the address. Returns 1 parameter but examples expect 2.
    - addIssuerCredential -> Compatible
    - updateCredentialStatus -> Compatible
    - deleteSubjectCredential -> Compatible with the lib. Not used by the examples
    - addSubjectCredential -> Compatible
    -

**Comment by msalitu** [comment]
Please @nefera606 confirm us that this findings are correct 👍

**Comment by nefera606** [comment]
I respond over the list of items, but contracts hasn't change too much, libs may be not need huge changes to be adapted:

AlastriaCredentialRegistry

    issuerCredentialList -> Should be recovered by the lib, not for the examples, but in future applications may be useful.
    getSubjectCredentialList -> Compatible
    version -> not needed from library, only for sc maintainability
    getSubjectCredentialStatus -> Compatible
    getCredentialStatus -> Compatible with the lib. Not used by the examples
    previousPublishedVersion -> will be removed soon (OZ upgradeablity)
    subjectCredentialRegistry -> Apps using library could be interested in recovering this information
    getIssuerCredentialStatus -> Compatible
    subjectCredentialList -> EXPECTS 2 parameters but lib only sends the address. Returns 1 parameter but examples expect 2. [Correct, can you fix library with this?]
    addIssuerCredential -> Compatible
    updateCredentialStatus -> Compatible
    deleteSubjectCredential -> Compatible with the lib. Not used by the examples
    addSubjectCredential -> Compatible

**Comment by nmanero** [comment]
Validation of AlastriaIdentityManager contract. Apart from unused methods, everything seems to be compatible.

- identityKeys -> Not used by the library but used in examples. Compatible.
- getEidasLevel -> Not used by the examples. Compatible
- addIdentityServiceProvider -> compatible
- setUrlLogo -> compatible
- transfer -> unused??
- setCifEntity -> compatible
- pendingIDs -> unused??
- isOwner -> unused??
- deleteIdentityServiceProvider -> compatible
- alastriaPresentationRegistry -> unused??
- updateIdentityIssuerEidasLevel -> lib compatible but unused by examples
- prepareAlastriaID -> compatible
- setUrlCreateAID -> compatible
- version
- delegateCall -> lib is compatible, unused by examples
- isIdentityIssuer ->  compatible
- createAlastriaIdentity -> compatible
- entitiesList -> compatible
- getEntity -> compatible
- addIdentityIssuer -> compatible
- owner
- setUrlAOA -> compatible
- addEntity -> compatible
- recoverAccount -> unused??
- deleteIdentityIssuer -> compatible
- isIdentityServiceProvider -> compatible
- setNameEntity -> compatible
- alastriaPublicKeyRegistry -> unused??

**Comment by msalitu** [comment]
Everything sounds right @nmanero, please @nefera606 could you confirm that there are no compatible issues to solve? 

I just want to point out that ```delegateCall``` function seems not to be used in the examples because it is internally used by the library. This means that the txFactory of the IdentityManager, CredentialsRegistry and PresentationsRegistry build properly the transaction using the defined pattern through the AlastriaProxy forward.

Thanks both!

**Comment by nmanero** [comment]
AlastriaPublicKeyRegistry:

- getPublicKeyStatus -> compatible, unused by examples
- getCurrentPublicKey -> compatible
- deletePublicKey -> compatible, unused by examples
- addKey -> compatible. In examples although it is mentioned in comments, it it not used
- version
- previousPublishedVersion
- publicKeyList -> unused
- revokePublicKey -> compatible, unused by the examples

**Comment by nmanero** [comment]
AlastriaPresentationRegistry:

- getPresentationStatus -> compatible
- subjectPresentationRegistry -> unused
- updateReceiverPresentation -> compatible
- addSubjectPresentation -> compatible
- getSubjectPresentationStatus -> compatible
- version
- previousPublishedVersion
- getReceiverPresentationStatus -> compatible
- getSubjectPresentationList -> compatible
- subjectPresentationListRegistry -> unused 
- updateSubjectPresentation -> compatible

**Comment by msalitu** [comment]
Thanks @nmanero, this scenario would be great because libraries should be already compatible!! Please @nefera606, could you confirm it?

**Comment by nefera606** [comment]
I see everything Ok, the methods reachable by the library are the ones needed.

**Comment by nmanero** [comment]
AlastriaIdentityEntity:

- setUrlLogo -> compatible, unused by examples
- setCifEntity -> compatible
- setUrlCreateAID -> compatible
- entitiesList -> compatible
- getEntity -> compatible
- setUrlAOA -> compatible
- addEntity -> compatible
- setNameEntity -> compatible

**Comment by nmanero** [comment]
identityIssuer

- getEidasLevel: compatible
- isIdentityIssuer: compatible
- addIdentityIssuer: compatible
- deleteIdentityIssuer: compatible

**Comment by nmanero** [comment]
AlastriaIdentityServiceProvider

- addIdentityServiceProvider: compatible
- deleteIdentityServiceProvider: compatible
- isIdentityServiceProvider: compatible

**Comment by nmanero** [comment]
Eidas

- atLeastLow: unused
- atLeast: unused

**Comment by msalitu** [comment]
Great job @nmanero. Everything is right.

Thank you!
