### ISSUE TITLE
Modificar referencia a SC al nuevo tag MVP01 en tsc

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#65]
Cambiar la referencia en el tsc de las librerías para que en vez de a develop apunte a master

Hacer una PR a master de las librerías

**Comment by msalitu** [comment]
https://github.com/alastria/alastria-identity/pull/98

**Comment by msalitu** [comment]
Para la release, hay que eliminar la restricción marcada en tokensFactory

Al inicio del fichero
// TODO: Remove when MVP is over
const MVP_CREDENTIAL_LIMIT = 2


En las funciones createPresentationRequest y en createPresentation
// TODO: Remove when MVP is over
  if (Object.keys(verifiableCredential).length > MVP_CREDENTIAL_LIMIT){
    throw new Error("You have exceeded the credential limit. Actual limit: " + MVP_CREDENTIAL_LIMIT)
  }

**Comment by DrankoLQ** [comment]
Una duda @msalitu : ¿el tsc que te refieres es el que aparce en el package.json? es el único que veo, además de su fichero de configuración `configFile.js`

```json
"compile": "git clone https://github.com/alastria/alastria-identity.git; node src/configFile.js; tsc",
```

**Comment by VictorNS69** [comment]
> Una duda @msalitu : ¿el tsc que te refieres es el que aparce en el package.json? es el único que veo, además de su fichero de configuración `configFile.js`
> 
> ```json
> "compile": "git clone https://github.com/alastria/alastria-identity.git; node src/configFile.js; tsc",
> ```
En principio, creo que ese clone pone por defecto la rama develop, así que creo que habría que hacer un clone de la rama especifica (master).

Que nos confirme las dudas @DaniRumpi

**Comment by DrankoLQ** [comment]
Es lo que yo supongo, pero como vi también el issue #64 que es parecido, por no decir lo mismo, no estaba seguro si se refería a otra cosa 😬

**Comment by VictorNS69** [comment]
Si, me parece que es el mismo problema ... jaja

**Comment by DaniRumpi** [comment]
Hola buenas. Ese clone si que va directo a la rama develop porque el repo está configurado para eso. Su rama principal el develop (a menos que se haya cambiado en estos días)

**Comment by DrankoLQ** [comment]
@msalitu esto está ya mergeado, pero en develop: me parecía mejor para revisarlo bien que se hiciera en dos pasos, primero a develop y luego a master, porque hay una diferencia muy grande entre master y develop (289 commits)

Me queda la duda de cuales deben ser los siguientes pasos, viendo los otros issues que hay creados:
- Probamos los examples apuntado a la rama develop de aquí, lo más actualizado, para comprobar que todos funcionan correctamente antes de mergear a master? (primero #63 y después #64 y #50 )
- Creo tag mvp0.1 y pull request de develop a master y cuando mergeemos hacemos la prueba de los examples usado el tag mvp0.1 como referencia (primero #64 y después #63 y #50)

Por mi parte, este issue podemos cerrarlo 🥳

**Comment by DrankoLQ** [comment]
Aclarado con @msalitu , cierro esto y me pongo con #64 para hacer la release mvp.01
