### ISSUE TITLE
U4 - createAlastriaSession

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#72]
Hay que corregir el context y el type:
-Context, que es un array de strings. La librería  debe introducir directamente la url de Alastria https://alastria.github.io/identity/artifacts/v1  En los tests se darán por válidas si hay más objetos en el array pero obligatoriamente uno debe ser esta url

- Type, que es un array de strings. La librería debe introducir directamente “AlastriaSession”. En los tests se dará por valido si hay más objetos en el array pero obligatoriamente uno de ellos debe ser “AlastriaSesion”

-Se debe modificar la clave “data” por “alastriaToken” tanto en la lib como en los tests

-Se debe eliminar el campo pku tanto en la lib porque la clave pública debe estar en el campo jwk del header

**Comment by Saithan16** [comment]
Hi,
The current JSON generated by the createAlastriaSession function doesn't have a header, should we add it?

**Comment by msalitu** [comment]
Yes, and it should have the same as the others: 

{
    "alg": "ES256K",
    "typ": "JWT",
    "kid": "did:ala:quor:redt:QmeeasCZ9jLbX...ueBJ7d7csxhb#keys-1",
    "jwk": "0x2e507af01167c98a6accc0cd46ab2a256dd6b6c69ec1c0c28f80fb62e1f7d70233768b0c58dbbdac1fc358b8141c075a520483cf9779e4ea98d13df2833f3767"
}

**Comment by Saithan16** [comment]
Ok, but then this function should still receive the 'pku' because its value is going to be the 'jwk' of the header, right?
