### ISSUE TITLE
FIX6 - Delegate calls AlastriaIdentityManager, AlastriaIssuers, AlastriaServiceProviders

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#88]
Añadir en IdentityManagerTransactionFactory.ts una función para que las llamadas al propio IdentityManager que tienen modifiers que comprueban el msg.sender se llamen a través del AlastriaProxy. Esta función debe invocarse desde todas las funciones asociadas a los smart contracts del IdentityManager, AlastriaIdentityServiceProvider y AlastriaIdentityServiceProvider
``` solidity
function delegated(web3, delegatedData) {
    return web3.eth.abi.encodeFunctionCall(
        config.contractsAbi["AlastriaIdentityManager"]["delegateCall"],
        [config.alastriaIdentityManager, 0, delegatedData])
  }
```
Después hay que añadir en cada función algo así:
```js
let delegatedData = web3.eth.abi.encodeFunctionCall(
        config.contractsAbi["AlastriaCredentialRegistry"]["updateCredentialStatus"],
        [issuerCredentialHash, status]);
transaction.data = delegated(web3, delegatedData);
```
La manera correcta de probarlo es que una vez que se modifique, cuando por ejemplo se haga un addIssuer se compruebe que la address que queda registrada es la del AlastriaProxy en vez de la address del keystore de tal manera que se pueda invocar al prepareAlastriaID

**Comment by VictorNS69** [comment]
Tras esta tarea se tendrá que lanzar una release 1.5 o borrar la release anterior y cambiarla con esta.
