### ISSUE TITLE
D3 - Divide alastria-identity-lib in alastriaid-lib-txsigner-eth

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-lib#96]
contendría lo que es actualmente UserIdentity que permite firmar las transacciones con un keystore. Se propone refactorizar el propio UserIdentity por Signer

**Comment by amoral-eurogestion** [comment]
No entiendo cómo tendría que hacer la partición, necesito saber la estructura de archivos y que poner en cada uno.
En referente a la refactorización, no entiendo que hace el código. Me parece entender que usa Ethereum, pero no tengo conocimientos de este o de transacciones web.
